---
- name: Help
  vars:
    my_tags: "{{ ansible_run_tags | difference(['all']) }}"
  when: (my_tags | length == 0) or (my_tags | intersect(certificate_known_tags) | length == 0)

  block:
    - name: "Help: Help"
      ansible.builtin.debug:
        msg: "{{ '{}'.format(certificate_help_text) }}"
    - name: "Help: End play"
      ansible.builtin.meta: end_play

# EOF
