---

# FreeBSD
- name: "packages: Install packages FreeBSD"
  community.general.pkgng:
    name: "{{ certificate_packages + certificate_packages2 }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when:
    - ansible_os_family == 'FreeBSD'
    - freebsd_install_method|lower == 'packages'

- name: "packages: Install ports FreeBSD"
  community.general.portinstall:
    name: "{{ item }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  loop: "{{ certificate_packages + certificate_packages2 }}"
  when:
    - ansible_os_family == 'FreeBSD'
    - freebsd_install_method|lower == 'ports'

# Linux
- name: "packages: Install packages Linux"
  ansible.builtin.package:
    name: "{{ certificate_packages + certificate_packages2 }}"
  register: result
  retries: "{{ linux_install_retries }}"
  until: result is succeeded
  delay: "{{ linux_install_delay }}"
  when: ansible_os_family in certificate_supported_linux_family

# EOF
...
