---
- name: Get meta-data and role_name
  when: certificate_sanity_platform | bool or certificate_sanity_ansible_version | bool
  block:

    - name: "Sanity: Get meta-data."
      when: galaxy_info is undefined
      ansible.builtin.include_vars:
        file: meta/main.yml

    - name: "Sanity: Get role_name."
      ansible.builtin.set_fact:
        al_sanity_role_name: "{{ role_name }}"

- name: "Sanity: Include al_sanity_platform from lib"
  when: certificate_sanity_platform | bool
  ansible.builtin.include_role:
    name: "{{ certificate_ansible_lib[ansible_role_name] }}"
    tasks_from: al_sanity_platform

- name: "Sanity: Include al_sanity_ansible_version from lib"
  when: certificate_sanity_ansible_version | bool
  ansible.builtin.include_role:
    name: "{{ certificate_ansible_lib[ansible_role_name] }}"
    tasks_from: al_sanity_ansible_version

- name: "Sanity: Include al_sanity_packages from lib"
  when: certificate_sanity_packages | bool
  ansible.builtin.include_role:
    name: "{{ certificate_ansible_lib[ansible_role_name] }}"
    tasks_from: al_sanity_packages

# EOF
