---

- name: "sanity: Get meta-data and role_name."
  block:
    - name: "sanity: Get meta-data."
      ansible.builtin.include_vars:
        file: meta/main.yml
      when: galaxy_info is undefined
    - name: "sanity: Get role_name."
      ansible.builtin.set_fact:
        al_sanity_role_name: "{{ role_name }}"
  when: certificate_sanity_platform|bool or
        certificate_sanity_ansible_version|bool

- name: "sanity: Include vbotka.ansible_lib al_sanity_platform."
  ansible.builtin.include_role:
    name: vbotka.ansible_lib
    tasks_from: al_sanity_platform
  when: certificate_sanity_platform|bool

- name: "sanity: Include vbotka.ansible_lib al_sanity_ansible_version."
  ansible.builtin.include_role:
    name: vbotka.ansible_lib
    tasks_from: al_sanity_ansible_version
  when: certificate_sanity_ansible_version|bool

- name: "sanity: Include vbotka.ansible_lib al_sanity_packages."
  ansible.builtin.include_role:
    name: vbotka.ansible_lib
    tasks_from: al_sanity_packages
  when: certificate_sanity_packages|bool

# EOF
...
