---
- name: Include OS vars
  block:

    - name: "Vars: Set variables for al_include_os_vars_path"
      ansible.builtin.set_fact:
        al_os_vars_path: "{{ role_path }}"

    - name: "Vars: Include OS vars"
      ansible.builtin.include_role:
        name: vbotka.ansible_lib
        tasks_from: al_include_os_vars_path_incr

- name: Set flavors
  when:
    - freebsd_flavors_enable | bool
    - ansible_os_family == 'FreeBSD'
  block:

    - name: "Vars: Set variables for al_bsd_ports_set_flavor"
      ansible.builtin.set_fact:
        al_bsd_ports_list: "{{ certificate_packages }}"
        al_bsd_ports_flavors: "{{ freebsd_flavors }}"

    - name: "Vars: Set flavor"
      ansible.builtin.include_role:
        name: vbotka.ansible_lib
        tasks_from: al_bsd_ports_set_flavor

    - name: "Vars: Get results"
      ansible.builtin.set_fact:
        certificate_packages: "{{ al_bsd_ports_list }}"

# EOF
