---
- name: Include OS vars
  block:

    - name: "Vars: Set variables for al_include_os_vars_path"
      ansible.builtin.set_fact:
        al_os_vars_path: "{{ role_path }}"

    - name: "Vars: Include OS vars"
      ansible.builtin.include_role:
        name: vbotka.ansible_lib
        tasks_from: al_include_os_vars_path_incr

- name: Set flavors
  when:
    - freebsd_flavors_enable | bool
    - ansible_os_family == 'FreeBSD'
  block:

    - name: "Vars: Set variables for al_bsd_ports_set_flavor"
      ansible.builtin.set_fact:
        al_bsd_ports_list: "{{ certificate_packages }}"
        al_bsd_ports_flavors: "{{ freebsd_flavors }}"

    - name: "Vars: Set flavor"
      ansible.builtin.include_role:
        name: vbotka.ansible_lib
        tasks_from: al_bsd_ports_set_flavor

    - name: "Vars: Get results"
      ansible.builtin.set_fact:
        certificate_packages: "{{ al_bsd_ports_list }}"

- name: Add certificate_data_simple to certificate_data
  when: certificate_data_simple | length > 0
  block:

    - name: "Vars: Add certificate_data_simple to certificate_data"
      ansible.builtin.set_fact:
        certificate_data: "{{ certificate_data + _data | from_yaml }}"
      vars:
        _data: |
          [{% for name in certificate_data_simple %}
          { CN: {{ name }},
          {% for k, v in certificate_data_simple_scheme.items() %}
          {{ k }}: {{ name }}.{{ v }},
          {% endfor %} },
          {% endfor %}]

# EOF
